source 'https://rubygems.org'
gem 'sinatra'            # The Framework
gem 'sinatra-contrib'    # Useful additional features
gem 'haml'               # The rendering engine
gem 'bcrypt-ruby'        # Security, hashing
gem 'require_relative'   # REALLY USEFUL
gem 'rdiscount'          # Markdown support
